name: nourex
description: "A nour ex app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Network Image
  cached_network_image: ^3.4.1

  # Network API
  dio: ^5.8.0+1

  # Logger
  pretty_dio_logger: ^1.4.0

  # Freezed for state management
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0

  # State Management
  flutter_bloc: ^9.1.1

  # Http Parser
  http_parser: ^4.1.2

  # Flutter Phoenix for state management
  flutter_phoenix: ^1.1.1

  # Dependency Injection
  get_it: ^8.0.3

  # Responsive UI
  flutter_screenutil: ^5.9.3

  # Json Serialization
  json_annotation: ^4.9.0

  # Easy Localization
  easy_localization: ^3.0.7+1
  flutter_easyloading: ^3.0.5
  loading_indicator: ^3.1.1
  flutter_spinkit: ^5.2.1

  # Lottie
  lottie: ^3.3.1

  # Secure Storage
  flutter_secure_storage: ^9.2.4

  # SVG
  flutter_svg: ^2.2.0

  # Toast Message
  fluttertoast: ^8.2.12

  # Image Picker
  image_picker: ^1.1.2

  # OTP Inputs
  pinput: ^5.0.1

  # Animation Navigation
  page_transition: ^2.2.1

  # Shared Preferences
  shared_preferences: ^2.5.3

  # Skeleton
  skeletonizer: ^1.4.3

  # Icons
  iconsax: ^0.0.8

  # URL Launcher
  url_launcher: ^6.3.1

  # App Icon
  flutter_launcher_icons: ^0.14.4

  # Google Fonts
  google_fonts: ^6.2.1

  # Mime
  mime: ^2.0.0

  # Share App
  share_plus: ^11.0.0

  # Local Notification
  flutter_local_notifications: ^19.2.1

  # Top SnackBar
  top_snackbar_flutter: ^3.3.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/pngs/nourex_logo.png"

flutter:
  uses-material-design: true

  # assets:
  assets:
    - assets/pngs/
    - assets/svgs/
    - assets/animations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
