// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8JHfzx_e77VHlCWHSNM8SfE4eCmgb2T0',
    appId: '1:644432752969:web:e8595a5870df6be8c6ea98',
    messagingSenderId: '644432752969',
    projectId: 'noorex-8f738',
    authDomain: 'noorex-8f738.firebaseapp.com',
    storageBucket: 'noorex-8f738.firebasestorage.app',
    measurementId: 'G-LTF368MCLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2mW6d4dSLuMFSEj4v-7-51hwp3N5UI_4',
    appId: '1:644432752969:android:fe49db349fdc12fdc6ea98',
    messagingSenderId: '644432752969',
    projectId: 'noorex-8f738',
    storageBucket: 'noorex-8f738.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArT_7Ejopb79kSnrdgP7YIU3etblJzIoE',
    appId: '1:644432752969:ios:efc2479cb4576472c6ea98',
    messagingSenderId: '644432752969',
    projectId: 'noorex-8f738',
    storageBucket: 'noorex-8f738.firebasestorage.app',
    iosBundleId: 'com.nourex.nourex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArT_7Ejopb79kSnrdgP7YIU3etblJzIoE',
    appId: '1:644432752969:ios:efc2479cb4576472c6ea98',
    messagingSenderId: '644432752969',
    projectId: 'noorex-8f738',
    storageBucket: 'noorex-8f738.firebasestorage.app',
    iosBundleId: 'com.nourex.nourex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8JHfzx_e77VHlCWHSNM8SfE4eCmgb2T0',
    appId: '1:644432752969:web:2ccc75501c095db3c6ea98',
    messagingSenderId: '644432752969',
    projectId: 'noorex-8f738',
    authDomain: 'noorex-8f738.firebaseapp.com',
    storageBucket: 'noorex-8f738.firebasestorage.app',
    measurementId: 'G-HZH0SYS72F',
  );
}
